In [45]:
import numpy as np
import cv2 as cv
from skimage import io
import matplotlib.pyplot as plt
from scipy import fftpack
import matplotlib.image as mpimg

In [46]:
src1 = mpimg.imread('b1.jpg')
src2 = mpimg.imread('b2.jpg')
src3 = mpimg.imread('a1.jpg')
src4 = mpimg.imread('a2.jpg')

In [47]:
f = np.fft.fft2(src1) ## Fourier Transform
fshift = np.fft.fftshift(f) ## Shifting zero frequency to center
freq_spec = 20*np.log(np.abs(fshift))  ## Take absolute and log only for displaying purpo

mean = freq_spec[0][0]
print (mean)

[ 19.45910149 122.40594838  19.45910149]


In [59]:
f = np.fft.fft2(src2) ## Fourier Transform
fshift = np.fft.fftshift(f) ## Shifting zero frequency to center
freq_spec = 20*np.log(np.abs(fshift))  ## Take absolute and log only for displaying purpo

mean = freq_spec[0][0]
print (mean)

[54.48814298 86.95350588 69.62837121]


In [49]:
f = np.fft.fft2(src3) ## Fourier Transform
fshift = np.fft.fftshift(f) ## Shifting zero frequency to center
freq_spec = 20*np.log(np.abs(fshift))  ## Take absolute and log only for displaying purpo

mean = freq_spec[0][0]
print (mean)

[ 96.13550799 144.41282412  96.61584407]


In [50]:
f = np.fft.fft2(src4) ## Fourier Transform
fshift = np.fft.fftshift(f) ## Shifting zero frequency to center
freq_spec = 20*np.log(np.abs(fshift))  ## Take absolute and log only for displaying purpo

mean = freq_spec[0][0]
print (mean)

[ 54.84796933 138.51190394  54.84796933]


In [111]:

def detectrightness1(img):
    f = np.fft.fft2(img) ## Fourier Transform
    fshift = np.fft.fftshift(f) ## Shifting zero frequency to center
    freq_spec = 20*np.log(np.abs(fshift))  ## Take absolute and log only for displaying purpo
    mean = freq_spec[0][0]
    if mean [0] == mean [2]:
        print ("The image is in daylight")
    else:
        print("The image is taken at night")

In [112]:
detectrightness1(src1)

The image is taken at night


In [113]:
detectrightness1(src2)

The image is taken at night


In [114]:
def detectrightness2(img):
    f = np.fft.fft2(img) ## Fourier Transform
    fshift = np.fft.fftshift(f) ## Shifting zero frequency to center
    freq_spec = 20*np.log(np.abs(fshift))  ## Take absolute and log only for displaying purpo
    mean = freq_spec[0][0]
    if mean [0] == mean [2]:
        print ("The image is taken at night")
    else:
        print ("The image is in daylight")

In [120]:
detectrightness2(src3)

The image is in daylight


In [118]:
detectrightness2(src4)

The image is in daylight
